package com.nf147.ssm.dao;

import com.nf147.ssm.entity.Ran;
import java.util.List;

public interface RanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ran
     *
     * @mbg.generated
     */
    int insert(Ran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ran
     *
     * @mbg.generated
     */
    List<Ran> selectAll();
}