package com.nf147.ssm.entity;

import java.util.List;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_id
     *
     * @mbg.generated
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_name
     *
     * @mbg.generated
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_phone
     *
     * @mbg.generated
     */
    private String authorPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_address
     *
     * @mbg.generated
     */
    private String authorAddress;

    private List<Post> posts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_id
     *
     * @return the value of author.author_id
     *
     * @mbg.generated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_id
     *
     * @param authorId the value for author.author_id
     *
     * @mbg.generated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_name
     *
     * @return the value of author.author_name
     *
     * @mbg.generated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_name
     *
     * @param authorName the value for author.author_name
     *
     * @mbg.generated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_phone
     *
     * @return the value of author.author_phone
     *
     * @mbg.generated
     */
    public String getAuthorPhone() {
        return authorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_phone
     *
     * @param authorPhone the value for author.author_phone
     *
     * @mbg.generated
     */
    public void setAuthorPhone(String authorPhone) {
        this.authorPhone = authorPhone == null ? null : authorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_address
     *
     * @return the value of author.author_address
     *
     * @mbg.generated
     */
    public String getAuthorAddress() {
        return authorAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_address
     *
     * @param authorAddress the value for author.author_address
     *
     * @mbg.generated
     */
    public void setAuthorAddress(String authorAddress) {
        this.authorAddress = authorAddress == null ? null : authorAddress.trim();
    }
}